# run: conda env create --file environment.yml
name: plantcv
dependencies:
  - python=3.7
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image
  - scikit-learn
  - plotnine
  - nb_conda
  - opencv<3.10, >=3.4
channels:
  - defaults
  - conda-forge
